
byte* getCurrentSprite();
void processCommand(String command);
void printAndShiftNewspaper();
void printAndShiftEnvelope();
void printAndShiftFacebook();
void envelopeAnimation();
void scrollNewspaperAnimation();
void animateFixedSprite();
void setTimeFromString(String s);
void blinkWeekDays();
void flushBuffer();
void drawBuffer(int start);
void drawBufferLast32Byte();
void shiftDraw();
void shiftDrawFrom(int start);
void shiftCompleteBuffer(int shift);
void shiftDrawCompleteBuffer();
void drawClessidra();
void moveSand();
void drawDays();
void blinkAsSunday();
void blinkAsMonday();
void blinkAsTuesday();
void blinkAsWednesday();
void blinkAsThursday();
void blinkAsFriday();
void blinkAsSaturday();
void blinkDots();
void draw8x8(byte draw[8], int device);
void drawFirstDigit(byte * number);
void drawSecondDigit (byte * number);
void drawThirdDigit(byte * number);
void drawFourthDigit(byte * number);
void shiftSave(byte * in, byte * out, int shift, boolean right);
void drawTime();
byte* switchDigit(int d);
void clearDigits();
void setLedUnbounded(int j, int i, boolean value);
void clearWhole();
void drawColumn(int col, byte val);
void drawStringStatic(char* s, int length);
void fakeSetLedUnbounded(int j, int i, boolean value);
void fakeDrawColumn(int col, byte val);
void fakeDrawBuffer();
void status2Buf();
void drawClockOnBuffer();
void draw8x8OnBuffer(byte draw[8], int device);
void drawFirstDigitOnBuffer(byte * number);
void drawSecondDigitOnBuffer (byte * number);
void drawThirdDigitOnBuffer(byte * number);
void drawFourthDigitOnBuffer(byte * number);
void drawTimeOnBuffer();
void drawClessidraOnBuffer();
void setLedOnBuffer(int device, int row, int column, boolean foo);
void drawDaysOnBuffer();
void drawClock();
void forceDrawThirdDigit();
void clearBufferByDevice(int device);
void setTimeFromEEPROM();
void saveTimeToEEPROM(String s);
